import 'package:flutter/material.dart';
import 'package:flutter_bmi_calculator/Models/LoaiMayTinh.dart';
import 'package:flutter_bmi_calculator/Models/MayTinh.dart';
const FAKE_MT = const[
  LoaiMT(id: 1, tenloai: 'Asus', color: Colors.greenAccent),
  LoaiMT(id: 2, tenloai: 'Dell', color: Colors.limeAccent),
  LoaiMT(id: 3, tenloai: 'Macbook', color: Colors.cyan),
  LoaiMT(id: 4, tenloai: 'HP', color: Colors.pinkAccent),
  LoaiMT(id: 5, tenloai: 'Lenovo', color: Colors.deepOrange),
  LoaiMT(id: 6, tenloai: 'Acer', color: Colors.teal),
  LoaiMT(id: 7, tenloai: 'MSI', color: Colors.grey),
  LoaiMT(id: 8, tenloai: 'Surface', color: Colors.deepPurpleAccent),
];
var Fake_MayTinh = [
  MayTinh(tenmaytinh: 'Asus', urlimage: 'assets/images/asus.jpg', ingredients: ['Laptop Asus Vivobook',
    '18.890.000đ'
    'Intel Core i5-1135G7',
    '8 GB, DDR4, 3200 MHz',
    'SSD 512 GB',
    'Intel Iris Xe Graphics',
    ],idloai: 1),
  MayTinh(tenmaytinh: 'Asus',
      urlimage: 'assets/images/asus1.jpg', ingredients: ['Laptop Asus Zenbook 14 UX434FLC-A6212T',
    '15.999.000₫',
    'CPU: Intel Core i5-10210U (1.60GHz upto 4.20GHz, 6MB)',
    '8 GB, LPDDR4X, 4266 MHz',
    'SSD 512 GB',
    'Intel Iris Xe Graphics',
    ],idloai: 1),
  MayTinh(tenmaytinh: 'Asus',
      urlimage: 'assets/images/asus2.jpg', ingredients: ['ASUS VivoBook S14 S433EA-AM440T',
        '19.999.000₫',
        'Intel Core i5-10210U 1,6 GHz',
        '8 GB',
        'SSD 512 GB',
        'Intel Iris Xe Graphics',
      ],idloai: 1),
  MayTinh(tenmaytinh: 'Dell',
      urlimage: 'assets/images/dell.jpg', ingredients: ['Dell XPS 13 9333',
        '12.900.000đ',
        'Intel Core i7 4500U',
        '8GB PC3L bus 1600',
        'SSD 256GB',
        'Intel Graphics 4400',
      ],idloai: 2),
  MayTinh(tenmaytinh: 'Dell',
      urlimage: 'assets/images/dell1.jpg', ingredients: ['Dell Inspiron 7460',
        '23,590,000đ',
        'Intel Core i7 7500U ',
        '8G DDR4 2400Mhz',
        '128Gb SSD // HDD 1000GB',
        'Intel HD Graphics',
      ],idloai: 2),
  MayTinh(tenmaytinh: 'Dell',
      urlimage: 'assets/images/dell2.jpg', ingredients: ['DELL INSPIRON 3501',
        '21.990.000đ',
        'i51135G72.4GHz',
        '	8GB DDR4',
        'HDD SATASSD 512 GB NVMe PCIe',
        'NVIDIA GeForce MX330',
      ],idloai: 2),
  MayTinh(tenmaytinh: 'Surface',
      urlimage: 'assets/images/sur.jpg', ingredients: ['SURFACE BOOK',
        '16.000.000đ',
        'Intel Core i5 6300U',
        '8 GB',
        '128 GB SSD',
        ' Intel HD Graphics 520',
      ],idloai: 8),
  MayTinh(tenmaytinh: 'Surface',
      urlimage: 'assets/images/sur1.jpg', ingredients: ['SURFACE BOOK',
        '23.900.000đ',
        'Intel Core i7 6600U',
        '16 GB',
        '512 GB SSD',
        'Intel HD Graphics 520',
      ],idloai: 8),
  MayTinh(tenmaytinh: 'Surface',
      urlimage: 'assets/images/sur2.jpg', ingredients: ['SURFACE BOOK 2',
        '33.500.000đ ',
        'Intel Core i7 8650U',
        '16 GB',
        '512 GB SSD',
        'Intel HD Graphics 620',
      ],idloai: 8),
  MayTinh(tenmaytinh: 'MacBook',
      urlimage: 'assets/images/mac1.jpg', ingredients: ['MacBook Pro M1 256GB 13.3-inch',
        '32.000.000đ ',
        'Apple M1 chip with 8-core CPU, 8-core GPU, 16-core Neural Engine',
        '8GB ',
        '256GB',
        'Intergrateds Graphics: 8-core GPU',
      ],idloai: 3),

  MayTinh(tenmaytinh: 'MacBook',
      urlimage: 'assets/images/mac2.jpg', ingredients: ['MacBook Pro 16-inch M1 Max 32GB',
        '95.000.000đ',
        'Apple M1 Max chip with 10-core CPU, 32-core GPU, and 16-core Neural Engine',
        '32GB',
        '1TB SSD',
        'Intergrated Graphics: 32-core GPU',
      ],idloai: 3),
  MayTinh(tenmaytinh: 'HP',
      urlimage: 'assets/images/hp1.jpg', ingredients: ['Laptop HP Pavilion 14-dv0012TU 2D7B7PA',
        '17.990.000đ',
        'Intel Core i5-1135G7',
        '8GB',
        '512GB PCIe NVMe M.2 SSD',
        'Intel Iris Xe Graphics',
      ],idloai: 4),
  MayTinh(tenmaytinh: 'HP',
      urlimage: 'assets/images/hp2.jpg', ingredients: ['Laptop HP 14-DQ2055WM',
        '13,900,000đ',
        'Core i3-1115G4',
        '4GB',
        'SSD 256GB M2-PCIe',
        'Intel UHD Graphics',
      ],idloai: 4),
  MayTinh(tenmaytinh: 'HP',
      urlimage: 'assets/images/hp2.jpg', ingredients: ['Laptop HP 14-DQ2055WM',
        '13,900,000đ',
        'Core i3-1115G4',
        '4GB',
        'SSD 256GB M2-PCIe',
        'Intel UHD Graphics',
      ],idloai: 4),
  MayTinh(tenmaytinh: 'HP',
      urlimage: 'assets/images/hp3.jpg', ingredients: ['HP 14s-dq2518TU',
        '5,499,000đ',
        'Intel Celeron 6305U ',
        '4GB',
        '512GB SSD NVME',
        'Intel UHD Graphics',
      ],idloai: 4),
  MayTinh(tenmaytinh: 'Lenovo',
      urlimage: 'assets/images/lenovo1.jpg', ingredients: ['Laptop Lenovo Thinkbook 14 G2 ITL 20VD004BVN',
        '18.190.000đ',
        'Core i5 1135G7 2.4 Ghz ',
        '8Gb',
        '256Gb SSD',
        'Intel Iris Xe Graphics',
      ],idloai: 5),
  MayTinh(tenmaytinh: 'Lenovo',
      urlimage: 'assets/images/lenovo2.jpg', ingredients: ['Lenovo ThinkPad T14 Gen 2 ',
        '31.900.000đ',
        'Intel Core i7 1165G7 2.8GHz ',
        '16GB',
        '512GB SSD',
        'NVIDIA GeForce MX450 ',
      ],idloai: 5),
  MayTinh(tenmaytinh: 'Lenovo',
      urlimage: 'assets/images/lenovo3.jpg', ingredients: ['Laptop Lenovo Thinkpad T490 ',
        '22.900.000đ',
        'Intel Core  i7-8565U ',
        '8GB',
        'SSD 256GB',
        'Intel UHD Graphics 620',
      ],idloai: 5),
  MayTinh(tenmaytinh: 'Acer',
      urlimage: 'assets/images/acer.jpg', ingredients: ['Laptop Acer Aspire 3',
        '7.679.000đ',
        'Intel Pentium N5000',
        '4GB',
        '256GB SSD',
        'Onboard',
      ],idloai: 6),
  MayTinh(tenmaytinh: 'Acer',
      urlimage: 'assets/images/acer1.jpg', ingredients: ['LAPTOP ACER GAMING NITRO 5 AN515-43-R4VJ',
        '19.899.000đ',
        'AMD Ryzen 7 3750H',
        '8GB',
        '512GB SSD',
        'GTX1650 4G',
      ],idloai: 6),
  MayTinh(tenmaytinh: 'Acer',
      urlimage: 'assets/images/acer2.jpg', ingredients: ['Laptop Acer Aspire 3',
        '13.490.000đ',
        'Core i5-1035G1',
        '4GB ',
        '256GB SSD',
        'Intel UHD Graphics',
      ],idloai: 6),
  MayTinh(tenmaytinh: 'MSI',
      urlimage: 'assets/images/msi.jpg', ingredients: ['Laptop MSI Gaming GF65 Thin 10SER 622VN',
        '30.690.000đ',
        'Core i7 10750H 2.6Ghz-12MB',
        '8GB ',
        '512GB SSD',
        'Nvidia RTX2060 6GB DDR6',
      ],idloai: 7),
  MayTinh(tenmaytinh: 'MSI',
      urlimage: 'assets/images/msi1.jpg', ingredients: ['Laptop MSI Gaming Katana GF66 11UD 697VN',
        '30.999.000đ',
        'Intel Core i7-11800H',
        '8GB ',
        '512GB SSD',
        'NVIDIA GeForce GTX 3050 4GB',
      ],idloai: 7),
  MayTinh(tenmaytinh: 'MSI',
      urlimage: 'assets/images/msi2.jpg', ingredients: ['Laptop MSI Modern 15 A11M',
        '18.879.000đ',
        'Intel Core i5 1135G7',
        '8GB ',
        '512GB SSD',
        'Onboard',
      ],idloai: 7),
];